// Chapter #1


// Q1
// alert("Hello Welcome");

// Q2
// alert("Error! Please enter a valid password.")

// Q3
// alert("Welcome to JS Land... \n Happy coding")

// Q4
// alert(" Welcome to JS land...")
// alert("Happy coding! \n Pervent this page from creating additonal dialoud")

// Q5
// alert(" Hello... I can run JS through my web browser's console")

// Q6 & Q7 
// Done

// CHAPTER #2

// Q1
// var username=

// Q2
// var myname = "Arshamirali"

// Q3
// var message="HEllO WORLD"
// alert(message)

// Q4(A)
// var student_name ="JHONE DOE"
// alert(student_name)

// Q4(B)
// var age="15 years old"
// alert(age)

// Q4(C)
// var profession="Certified Mobile Application Developer"
// alert(profession)

// Q5
// alert("PIZZA \n PIZZ \n PIZ \n PI \n P")

// Q6
// var email="example@example.com"
// alert("My email is"+" "+email)

// Q7
// var book="A smarter way to learn Java script"
// alert(book)

// Q8
// document.write("Yah! I can wirte HTML content through JavaScript")



