// Chapter #1
// Q1
// alert("Hello Welcome");

// Q2
// alert("Error! Please enter a valid password.")

// Q3
// alert("Welcome to JS Land... \n Happy coding")

// Q4
// alert(" Welcome to JS land...")
// alert("Happy coding! \n Pervent this page from creating additonal dialoud")

// Q5
// alert(" Hello... I can run JS through my web browser's console")

// Q6 & Q7 
// Done

//-----------------x---------------x----------x-----------------x------------x--- 

// CHAPTER #2
// Q1
// var username=

// Q2
// var myname = "Arshamirali"

// Q3
// var message="HEllO WORLD"
// alert(message)

// Q4(A)
// var student_name ="JHONE DOE"
// alert(student_name)

// Q4(B)
// var age="15 years old"
// alert(age)

// Q4(C)
// var profession="Certified Mobile Application Developer"
// alert(profession)

// Q5
// alert("PIZZA \n PIZZ \n PIZ \n PI \n P")

// Q6
// var email="example@example.com"
// alert("My email is"+" "+email)

// Q7
// var book="A smarter way to learn Java script"
// alert(book)

// Q8
// document.write("Yah! I can wirte HTML content through JavaScript")

// ----------------------x-----------------------x-------------x-------------x-------------------x-----

// Chapter #3
// Q1
// var age ="19"
// alert("I am"+" " + age +" "+" year old")

// Q2
// var record=14
// alert("You have visited this website"+" "+ record + " times")

// Q3
// var dob=2005
// document.write("MY BIRTH YEAR IS "+ dob +"<br> My data type of variable is number")

 // Q4
// var name ="Arsh"
// var order=4
// var product ="t-shirt"
// document.write( name+ " " +"ordered"+" "+order+" "+ product+ "on XYZ Clothing store.")

// -------------------x------------x----------x--------------x---------------x-----------------------x---------x--

// Chapter #5
// Q1
// var name="arsh" , var age=19 , var dob=2005

// Q2
// illegal
// var 125name
// var @name
// var #name
// var 12356
// var (dwed)

// legal
// var Name_full
// var nameFull
// var $namefull
// var namefull$
// var namefull2005

// Q3
document.write(" A heading stating “Rules for naming JS variables <br> b) Variable names can only contain ______, ______, ______ and ______. <br> For example $my_1stVariable  <br> c) Variables must begin with a ______, ______ or_____. For example $name, _name or name <br> d) Variable names are case _________ <br> e) Variable names should not be JS _________ ")